INSERT INTO analytics.dim_companies
(ticker,company_name,sector,industry,market_cap_tier,nifty50_member,sensex_member,is_commodity,is_index,currency,exchange)
VALUES
('TCS.NS','Tata Consultancy Services','IT','IT Services','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('INFY.NS','Infosys','IT','IT Services','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('WIPRO.NS','Wipro','IT','IT Services','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('HCLTECH.NS','HCL Technologies','IT','IT Services','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('TECHM.NS','Tech Mahindra','IT','IT Services','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('LTIM.NS','LTIMindtree','IT','IT Services','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('MPHASIS.NS','Mphasis','IT','IT Services','Mid Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('PERSISTENT.NS','Persistent Systems','IT','IT Services','Mid Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('COFORGE.NS','Coforge','IT','IT Services','Mid Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('OFSS.NS','Oracle Financial Services','IT','IT Services','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('HDFCBANK.NS','HDFC Bank','Banking','Private Bank','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('ICICIBANK.NS','ICICI Bank','Banking','Private Bank','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('KOTAKBANK.NS','Kotak Mahindra Bank','Banking','Private Bank','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('SBIN.NS','State Bank of India','Banking','Public Bank','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('AXISBANK.NS','Axis Bank','Banking','Private Bank','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('BAJFINANCE.NS','Bajaj Finance','Banking','NBFC','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('BAJAJFINSV.NS','Bajaj Finserv','Banking','Financial Services','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('INDUSINDBK.NS','IndusInd Bank','Banking','Private Bank','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('PNB.NS','Punjab National Bank','Banking','Public Bank','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('HDFCLIFE.NS','HDFC Life Insurance','Banking','Insurance','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('SUNPHARMA.NS','Sun Pharmaceutical','Pharma','Pharmaceuticals','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('DRREDDY.NS','Dr Reddys Laboratories','Pharma','Pharmaceuticals','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('CIPLA.NS','Cipla','Pharma','Pharmaceuticals','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('DIVISLAB.NS','Divis Laboratories','Pharma','Pharmaceuticals','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('APOLLOHOSP.NS','Apollo Hospitals','Pharma','Healthcare','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('TORNTPHARM.NS','Torrent Pharmaceuticals','Pharma','Pharmaceuticals','Mid Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('AUROPHARMA.NS','Aurobindo Pharma','Pharma','Pharmaceuticals','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('LUPIN.NS','Lupin','Pharma','Pharmaceuticals','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('BIOCON.NS','Biocon','Pharma','Biotechnology','Mid Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('MAXHEALTH.NS','Max Healthcare','Pharma','Healthcare','Mid Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('RELIANCE.NS','Reliance Industries','Energy','Conglomerate','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('ONGC.NS','Oil Natural Gas Corp','Energy','Oil & Gas','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('NTPC.NS','NTPC Limited','Energy','Power Generation','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('POWERGRID.NS','Power Grid Corporation','Energy','Power Transmission','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('IOC.NS','Indian Oil Corporation','Energy','Oil & Gas','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('ADANIGREEN.NS','Adani Green Energy','Energy','Renewable Energy','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('TATAPOWER.NS','Tata Power','Energy','Power Generation','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('COALINDIA.NS','Coal India','Energy','Mining','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('BPCL.NS','Bharat Petroleum','Energy','Oil & Gas','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('ADANIPORTS.NS','Adani Ports & SEZ','Energy','Infrastructure','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('HINDUNILVR.NS','Hindustan Unilever','FMCG','Consumer Goods','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('ITC.NS','ITC Limited','FMCG','Diversified FMCG','Large Cap',TRUE,TRUE,FALSE,FALSE,'INR','NSE'),
('NESTLEIND.NS','Nestle India','FMCG','Food & Beverages','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('BRITANNIA.NS','Britannia Industries','FMCG','Food & Beverages','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('DABUR.NS','Dabur India','FMCG','Consumer Goods','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('MARICO.NS','Marico','FMCG','Consumer Goods','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('GODREJCP.NS','Godrej Consumer Products','FMCG','Consumer Goods','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('COLPAL.NS','Colgate-Palmolive India','FMCG','Consumer Goods','Large Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('EMAMILTD.NS','Emami','FMCG','Consumer Goods','Mid Cap',FALSE,FALSE,FALSE,FALSE,'INR','NSE'),
('TATACONSUM.NS','Tata Consumer Products','FMCG','Food & Beverages','Large Cap',TRUE,FALSE,FALSE,FALSE,'INR','NSE'),
('GC=F','Gold Futures','Commodity','Precious Metal',NULL,FALSE,FALSE,TRUE,FALSE,'USD','COMEX'),
('CL=F','Crude Oil WTI','Commodity','Energy',NULL,FALSE,FALSE,TRUE,FALSE,'USD','NYMEX'),
('SI=F','Silver Futures','Commodity','Precious Metal',NULL,FALSE,FALSE,TRUE,FALSE,'USD','COMEX'),
('^NSEI','NIFTY 50','Index','Broad Market',NULL,FALSE,FALSE,FALSE,TRUE,'INR','NSE'),
('^BSESN','BSE SENSEX','Index','Broad Market',NULL,FALSE,FALSE,FALSE,TRUE,'INR','BSE'),
('^NSEBANK','NIFTY Bank','Index','Banking',NULL,FALSE,FALSE,FALSE,TRUE,'INR','NSE'),
('^CNXIT','NIFTY IT','Index','IT',NULL,FALSE,FALSE,FALSE,TRUE,'INR','NSE'),
('^INDIAVIX','India VIX','Index','Volatility',NULL,FALSE,FALSE,FALSE,TRUE,'INR','NSE'),
('USDINR=X','USD INR Rate','Forex','Currency',NULL,FALSE,FALSE,FALSE,TRUE,'INR','FOREX')
ON CONFLICT (ticker) DO NOTHING;
